### ISSUE TITLE
After Clicking Next Step Website is not showing any valid emails

### ISSUE THREAD

**Issue by MayankMaloo192** [Shruthi-Sivagnanam/emailHunt#1]

**Comment by MayankMaloo192** [comment]
Website not showing valid emails after submitting csv file .

**Comment by Shruthi-Sivagnanam** [comment]
Can you please share the csv file to me. So that I can make a check on it.

I tested this application with 1400+ emails for classifying valid and invalid emails, it worked perfectly.


![Screenshot (145)](https://github.com/Shruthi-Sivagnanam/emailHunt/assets/82823305/b9800e97-8ee6-49b3-93a6-d3bff523149c)
